VERSION="2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Redeaux Games, Inc."
ORG_DBA="MAGMA TOKEN"
ORG_URL="https://magm.red"
ORG_LOGO="https://magm.red/magm-token-stellar-sm.png"
ORG_DESCRIPTION="Issued by the developers of Redeaux Games."
ORG_PHYSICAL_ADDRESS="5570 FM 423 Suite 250, FRISCO, TX 75036, United States"
ORG_TWITTER="redeauxg"
ORG_GITHUB="floatbeta"
ORG_OFFICIAL_EMAIL="magma@redeaux.games"

[[PRINCIPALS]]
name="Redeaux Games"
email="dev@redeaux.games"
twitter="redeauxg"
github="floatbeta"


[[CURRENCIES]]
code="MAGM"
issuer="GCQQ3D37HAJPPNSJJ7546F6APLVETOOHAZHC2ZIX7GL533TDFDPAZVPS"
display_decimals= 7
name="MAGMA"
desc="MAGMA Token is a cross-chain token, that powers the economy in The Verse, an upcoming metaverse experience."
conditions="There will only ever be 777,000,000 MAGM tokens on the Stellar blockchain."
image="https://magm.red/magm-token-stellar-sm.png"
fixed_number= 777000000
