VERSION="2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Redeaux Games, Inc."
ORG_DBA="MAGMA TOKEN"
ORG_URL="https://magm.red"
ORG_LOGO="https://magm.red/magm-token-stellar-sm.png"
ORG_DESCRIPTION="Issued by the developers of Redeaux Games."
ORG_PHYSICAL_ADDRESS="5570 FM 423 Suite 250, FRISCO, TX 75036, United States"
ORG_TWITTER="redeauxg"
ORG_GITHUB="floatbeta"
ORG_KEYBASE="magma"
ORG_OFFICIAL_EMAIL="magma@redeaux.games"

[[PRINCIPALS]]
name="Redeaux Games"
email="dev@redeaux.games"
twitter="redeauxg"
github="floatbeta"

[[CURRENCIES]]
code="MAGM"
issuer="GCQQ3D37HAJPPNSJJ7546F6APLVETOOHAZHC2ZIX7GL533TDFDPAZVPS"
display_decimals= 7
name="MAGMA"
desc="MAGMA Token is a cross-chain token, that powers the economy in The Verse, an upcoming metaverse experience."
conditions="There will only ever be 777,000,000 MAGM tokens on the Stellar blockchain."
image="https://magm.red/magm-token-stellar-sm.png"
fixed_number= 777000000

[[HOME_DOMAINS]]
HOME_DOMAIN="www.stellar.org"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="lobstr.co"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="coinqvest.com"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="wirexapp.com"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="stellar.blockdaemon.com"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="keybase.io"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="satoshipay.io"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="validator.stellar.expert"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="publicnode.org"
QUALITY="HIGH"

[[HOME_DOMAINS]]
HOME_DOMAIN="fchain.io"
QUALITY="HIGH"

[[VALIDATORS]]
NAME="sdf_1"
HOME_DOMAIN="www.stellar.org"
PUBLIC_KEY="GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH"
ADDRESS="core-live-a.stellar.org"
HISTORY="curl -sf http://history.stellar.org/prd/core-live/core_live_001/{0} -o {1}"

[[VALIDATORS]]
NAME="sdf_2"
HOME_DOMAIN="www.stellar.org"
PUBLIC_KEY="GCM6QMP3DLRPTAZW2UZPCPX2LF3SXWXKPMP3GKFZBDSF3QZGV2G5QSTK"
ADDRESS="core-live-b.stellar.org"
HISTORY="curl -sf http://history.stellar.org/prd/core-live/core_live_002/{0} -o {1}"

[[VALIDATORS]]
NAME="sdf_3"
HOME_DOMAIN="www.stellar.org"
PUBLIC_KEY="GABMKJM6I25XI4K7U6XWMULOUQIQ27BCTMLS6BYYSOWKTBUXVRJSXHYQ"
ADDRESS="core-live-c.stellar.org"
HISTORY="curl -sf http://history.stellar.org/prd/core-live/core_live_003/{0} -o {1}"

[[VALIDATORS]]
NAME="LOBSTR_1_Europe"
HOME_DOMAIN="lobstr.co"
PUBLIC_KEY="GCFONE23AB7Y6C5YZOMKUKGETPIAJA4QOYLS5VNS4JHBGKRZCPYHDLW7"
ADDRESS="v1.stellar.lobstr.co"
HISTORY="curl -sf https://stellar-archive-1-lobstr.s3.amazonaws.com/{0} -o {1}"

[[VALIDATORS]]
NAME="LOBSTR_2_Europe_"
HOME_DOMAIN="lobstr.co"
PUBLIC_KEY="GDXQB3OMMQ6MGG43PWFBZWBFKBBDUZIVSUDAZZTRAWQZKES2CDSE5HKJ"
ADDRESS="v2.stellar.lobstr.co"
HISTORY="curl -sf https://stellar-archive-2-lobstr.s3.amazonaws.com/{0} -o {1}"

[[VALIDATORS]]
NAME="LOBSTR_3_North_America"
HOME_DOMAIN="lobstr.co"
PUBLIC_KEY="GD5QWEVV4GZZTQP46BRXV5CUMMMLP4JTGFD7FWYJJWRL54CELY6JGQ63"
ADDRESS="v3.stellar.lobstr.co"
HISTORY="curl -sf https://stellar-archive-3-lobstr.s3.amazonaws.com/{0} -o {1}"

[[VALIDATORS]]
NAME="LOBSTR_4_Asia"
HOME_DOMAIN="lobstr.co"
PUBLIC_KEY="GA7TEPCBDQKI7JQLQ34ZURRMK44DVYCIGVXQQWNSWAEQR6KB4FMCBT7J"
ADDRESS="v4.stellar.lobstr.co"
HISTORY="curl -sf https://stellar-archive-4-lobstr.s3.amazonaws.com/{0} -o {1}"

[[VALIDATORS]]
NAME="LOBSTR_5_Australia"
HOME_DOMAIN="lobstr.co"
PUBLIC_KEY="GA5STBMV6QDXFDGD62MEHLLHZTPDI77U3PFOD2SELU5RJDHQWBR5NNK7"
ADDRESS="v5.stellar.lobstr.co"
HISTORY="curl -sf https://stellar-archive-5-lobstr.s3.amazonaws.com/{0} -o {1}"
[[VALIDATORS]]
NAME="COINQVEST_Hong_Kong"
HOME_DOMAIN="coinqvest.com"
PUBLIC_KEY="GAZ437J46SCFPZEDLVGDMKZPLFO77XJ4QVAURSJVRZK2T5S7XUFHXI2Z"
ADDRESS="hongkong.stellar.coinqvest.com"
HISTORY="curl -sf https://hongkong.stellar.coinqvest.com/history/{0} -o {1}"

[[VALIDATORS]]
NAME="COINQVEST_Germany"
HOME_DOMAIN="coinqvest.com"
PUBLIC_KEY="GD6SZQV3WEJUH352NTVLKEV2JM2RH266VPEM7EH5QLLI7ZZAALMLNUVN"
ADDRESS="germany.stellar.coinqvest.com"
HISTORY="curl -sf https://germany.stellar.coinqvest.com/history/{0} -o {1}"

[[VALIDATORS]]
NAME="COINQVEST_Finland"
HOME_DOMAIN="coinqvest.com"
PUBLIC_KEY="GADLA6BJK6VK33EM2IDQM37L5KGVCY5MSHSHVJA4SCNGNUIEOTCR6J5T"
ADDRESS="finland.stellar.coinqvest.com"
HISTORY="curl -sf https://finland.stellar.coinqvest.com/history/{0} -o {1}"

[[VALIDATORS]]
NAME="wirexUS"
ADDRESS="us.stellar.wirexapp.com"
HOME_DOMAIN="wirexapp.com"
PUBLIC_KEY="GDXUKFGG76WJC7ACEH3JUPLKM5N5S76QSMNDBONREUXPCZYVPOLFWXUS"
HISTORY="curl -sf http://wxhorizonusstga1.blob.core.windows.net/history/{0} -o {1}"

[[VALIDATORS]]
NAME="wirexUK"
ADDRESS="uk.stellar.wirexapp.com"
HOME_DOMAIN="wirexapp.com"
PUBLIC_KEY="GBBQQT3EIUSXRJC6TGUCGVA3FVPXVZLGG3OJYACWBEWYBHU46WJLWXEU"
HISTORY="curl -sf http://wxhorizonukstga1.blob.core.windows.net/history/{0} -o {1}"

[[VALIDATORS]]
NAME="wirexSG"
ADDRESS="sg.stellar.wirexapp.com"
HOME_DOMAIN="wirexapp.com"
PUBLIC_KEY="GAB3GZIE6XAYWXGZUDM4GMFFLJBFMLE2JDPUCWUZXMOMT3NHXDHEWXAS"
HISTORY="curl -sf http://wxhorizonasiastga1.blob.core.windows.net/history/{0} -o {1}"
[[VALIDATORS]]
NAME="Blockdaemon_Validator_1"
HOME_DOMAIN="stellar.blockdaemon.com"
PUBLIC_KEY="GAAV2GCVFLNN522ORUYFV33E76VPC22E72S75AQ6MBR5V45Z5DWVPWEU"
ADDRESS="stellar-full-validator1.bdnodes.net"
HISTORY="curl -sf https://stellar-full-history1.bdnodes.net/{0} -o {1}"

[[VALIDATORS]]
NAME="Blockdaemon_Validator_2"
HOME_DOMAIN="stellar.blockdaemon.com"
PUBLIC_KEY="GAVXB7SBJRYHSG6KSQHY74N7JAFRL4PFVZCNWW2ARI6ZEKNBJSMSKW7C"
ADDRESS="stellar-full-validator2.bdnodes.net"
HISTORY="curl -sf https://stellar-full-history2.bdnodes.net/{0} -o {1}"

[[VALIDATORS]]
NAME="Blockdaemon_Validator_3"
HOME_DOMAIN="stellar.blockdaemon.com"
PUBLIC_KEY="GAYXZ4PZ7P6QOX7EBHPIZXNWY4KCOBYWJCA4WKWRKC7XIUS3UJPT6EZ4"
ADDRESS="stellar-full-validator3.bdnodes.net"
HISTORY="curl -sf https://stellar-full-history3.bdnodes.net/{0} -o {1}"
[[VALIDATORS]]
NAME="keybase.io"
HOME_DOMAIN="keybase.io"
PUBLIC_KEY="GCWJKM4EGTGJUVSWUJDPCQEOEP5LHSOFKSA4HALBTOO4T4H3HCHOM6UX"
ADDRESS="stellar0.keybase.io"
HISTORY="curl -sf https://stellarhistory.keybase.io/{0} -o {1}"

[[VALIDATORS]]
NAME="keybase1"
HOME_DOMAIN="keybase.io"
PUBLIC_KEY="GDKWELGJURRKXECG3HHFHXMRX64YWQPUHKCVRESOX3E5PM6DM4YXLZJM"
ADDRESS="stellar1.keybase.io"
HISTORY="curl -sf https://stellarhistory1.keybase.io/{0} -o {1}"

[[VALIDATORS]]
NAME="keybase2"
HOME_DOMAIN="keybase.io"
PUBLIC_KEY="GA35T3723UP2XJLC2H7MNL6VMKZZIFL2VW7XHMFFJKKIA2FJCYTLKFBW"
ADDRESS="stellar2.keybase.io"
HISTORY="curl -sf https://stellarhistory2.keybase.io/{0} -o {1}"
[[VALIDATORS]]
NAME="SatoshiPay_SG_Singapore"
HOME_DOMAIN="satoshipay.io"
PUBLIC_KEY="GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT"
ADDRESS="stellar-sg-sin.satoshipay.io"
HISTORY="curl -sf https://stellar-history-sg-sin.satoshipay.io/{0} -o {1}"

[[VALIDATORS]]
NAME="SatoshiPay_US_Iowa"
HOME_DOMAIN="satoshipay.io"
PUBLIC_KEY="GAK6Z5UVGUVSEK6PEOCAYJISTT5EJBB34PN3NOLEQG2SUKXRVV2F6HZY"
ADDRESS="stellar-us-iowa.satoshipay.io"
HISTORY="curl -sf https://stellar-history-us-iowa.satoshipay.io/{0} -o {1}"

[[VALIDATORS]]
NAME="SatoshiPay_DE_Frankfurt"
HOME_DOMAIN="satoshipay.io"
PUBLIC_KEY="GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE"
ADDRESS="stellar-de-fra.satoshipay.io"
HISTORY="curl -sf https://stellar-history-de-fra.satoshipay.io/{0} -o {1}"
[[VALIDATORS]]
NAME="StellarExpert-V1"
HOME_DOMAIN="validator.stellar.expert"
PUBLIC_KEY="GDQ75AS5VSH3ZHZI3P4TAVAOOSNHN346KXJOPZVQMMS27KNCC5TOQEXP"
ADDRESS="validator1.stellar.expert"
HISTORY="curl -sf http://history.validator1.stellar.expert/{0} -o {1}"

[[VALIDATORS]]
NAME="StellarExpert-V2"
HOME_DOMAIN="validator.stellar.expert"
PUBLIC_KEY="GCR64G344LXYVUD7523XGMMM2OEB4E6SPLIBHXNME5P6QYWAUF2QUTO3"
ADDRESS="validator2.stellar.expert"
HISTORY="curl -sf http://history.validator2.stellar.expert/{0} -o {1}"

[[VALIDATORS]]
NAME="StellarExpert-V3"
HOME_DOMAIN="validator.stellar.expert"
PUBLIC_KEY="GA23K4HUQMGXC46BGOSWY4AGRBB6ZWEOIF6N2ZUXS3X5A6FOMQPMIPEG"
ADDRESS="validator3.stellar.expert"
HISTORY="curl -sf http://history.validator3.stellar.expert/{0} -o {1}"
[[VALIDATORS]]
NAME="bootes"
HOME_DOMAIN="publicnode.org"
PUBLIC_KEY="GCVJ4Z6TI6Z2SOGENSPXDQ2U4RKH3CNQKYUHNSSPYFPNWTLGS6EBH7I2"
ADDRESS="bootes.publicnode.org"
HISTORY="curl -sf https://bootes-history.publicnode.org/{0} -o {1}"

[[VALIDATORS]]
NAME="hercules"
HOME_DOMAIN="publicnode.org"
PUBLIC_KEY="GBLJNN3AVZZPG2FYAYTYQKECNWTQYYUUY2KVFN2OUKZKBULXIXBZ4FCT"
ADDRESS="hercules.publicnode.org"
HISTORY="curl -sf https://hercules-history.publicnode.org/{0} -o {1}"

[[VALIDATORS]]
NAME="lyra"
HOME_DOMAIN="publicnode.org"
PUBLIC_KEY="GCIXVKNFPKWVMKJKVK2V4NK7D4TC6W3BUMXSIJ365QUAXWBRPPJXIR2Z"
ADDRESS="lyra.publicnode.org"
HISTORY="curl -sf https://lyra-history.publicnode.org/{0} -o {1}"

[[VALIDATORS]]
NAME="volans"
HOME_DOMAIN="publicnode.org"
PUBLIC_KEY="GAWG6BRIFFHATM2WVJ4AVQFK2K3GY3U4E6BWGOZQOI37BANBFCVOLANS"
ADDRESS="volans.publicnode.org"
HISTORY="curl -sf https://lyra-history.publicnode.org/{0} -o {1}"

[[VALIDATORS]]
NAME="vela"
HOME_DOMAIN="publicnode.org"
PUBLIC_KEY="GABUWARO3HUGOVU75R4M4YVYELFGOZNJAIE4PUDEJSPZJ5WKSZPNVELA"
ADDRESS="vela.publicnode.org"
HISTORY="curl -sf https://hercules-history.publicnode.org/{0} -o {1}"
[[VALIDATORS]]
NAME="fchain core1"
HOME_DOMAIN="fchain.io"
PUBLIC_KEY="GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U"
ADDRESS="140.82.49.116:11625"
HISTORY="curl -sf https://history1.stellar.yinghuo.io/{0} -o {1}"

[[VALIDATORS]]
NAME="fchain core2"
HOME_DOMAIN="fchain.io"
PUBLIC_KEY="GCORENF67J77JQNAVQT4RRQGPV2U2RPEMAI4ZPEDIHNVG2VXNTCJW4VX"
ADDRESS="66.42.52.36:11625"
HISTORY="curl -sf https://history2.stellar.yinghuo.io/{0} -o {1}"

[[VALIDATORS]]
NAME="fchain core3"
HOME_DOMAIN="fchain.io"
PUBLIC_KEY="GBCQK6PFPOJTKUQED2HVO3UVCG7RKSRIZSJMSXXLUHLX7OC2BBJC2JGZ"
ADDRESS="198.13.41.105:11625"
HISTORY="curl -sf https://history3.stellar.yinghuo.io/{0} -o {1}"

[[VALIDATORS]]
NAME="fchain core4"
HOME_DOMAIN="fchain.io"
PUBLIC_KEY="GBAIDU6UG32IDXE7WPP5AFZ2735CA3M7YDOQYONX4UNZCQEBPIVN5M7E"
ADDRESS="81.69.45.247:11625"
